### ISSUE TITLE
permissive license (not gpl)

### ISSUE THREAD

**Issue by notpeter** [Abbrahan/PlaydateTemplate-Linux-VSCode-C#1]
Hey,

I wanted to reach out and suggest you offer this under a more permissive license (CC0/MIT2/Apache).

By licensing this under the GPL you are suggesting that only GPL licensed projects may use your template severely limiting it's utility.  I appreciate you sharing your template for Playdate C  with VSCode on Linux -- it helps solves a real problem -- but practically speaking I'm not going to use or contribute (or even look at your code) if I know it can never be used on any project I intend to distribute.

You're not alone in applying restrictive licenses to code making it impossible to use examples as a the beginning of a real projects.  Panic similarly has a license for the examples in the SDK which prevents their use as a project template (which is dumb).

Thanks.

**Comment by Abbrahan** [comment]
Apologies as I seem to have misunderstood the restrictions placed by using GPL over something like CC0 or MIT/Apache. I checked the SDK License and you seem to be correct regarding distribution of the example projects since they are part of the SDK.

"
 You will not:

- Modify, disassemble, or decompile any part of the SDK;
- Distribute or transfer the SDK to others (other than the incorporation of distributable elements of the SDK in Your Developed Programs in accordance with the terms of this Agreement);
- Modify, adapt, alter, translate, or incorporate into or with other software or create a derivative work of any part of the SDK, except as permitted herein, without express written permission from Panic;
- Use the SDK to develop applications for other platforms or to develop another SDK, without express written permission from Panic.
"

Since I use the example C hello world program, I will need to take down this template for now until I can make a custom example C project to then publish along with this. I will then use the CC0 license for the template so that other developers can publish works without also needing to be published under the GPL license.
